
project_id = "mtyfuwdsshlzqwjujavp"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[realtime]
enabled = true

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[analytics]
enabled = true

[functions.create-db-trigger]
verify_jwt = false

