
project_id = "mtyfuwdsshlzqwjujavp"

[functions_config]
node_version = 18

[[functions]]
name = "shopify-auth"
verify_jwt = false

[[functions]]
name = "shopify-callback"
verify_jwt = false

[[functions]]
name = "shopify-products"
verify_jwt = true

[[functions]]
name = "shopify-sync-form"
verify_jwt = true

[[functions]]
name = "shopify-test-connection"
verify_jwt = true

[[functions]]
name = "shopify-theme-updater"
verify_jwt = true

[[functions]]
name = "update-schema"
verify_jwt = false

[[functions]]
name = "update-shopify-token"
verify_jwt = false

[[functions]]
name = "api-forms"
verify_jwt = false

[[functions]]
name = "api-submissions"
verify_jwt = false
