
# This file is used to configure the Supabase CLI
project_id = "nhqrngdzuatdnfkihtud"

[api]
# Port to start the API server on
port = 54321
# Schemas to expose in your API
schemas = ["public"]
# Extra schemas to expose in your API but exclude from automatic type generation
extra_schemas = ["storage", "auth"]

[db]
# Port to start the DB on
port = 54320

[studio]
# Port to start Studio on
port = 54323
# External URL for serving your API
api_url = "http://localhost:54321"
# External URL for serving the Supabase Studio
studio_url = "http://localhost:54323"
# External URL for serving the Inbucket UI
inbucket_url = "http://localhost:54324"

[functions]
[functions.shopify-auth]
verify_jwt = false

[functions.shopify-callback]
verify_jwt = false
