# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "753bee28b4a0b12f2d87c79b56c86641"
name = "CodMagnet - COD Form"
handle = "codform-cod-forms"
application_url = "https://codmagnet.com"
embedded = false

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "customers/data_request" ]
  uri = "/webhooks/customers/data_request"

  [[webhooks.subscriptions]]
  topics = [ "customers/redact" ]
  uri = "/webhooks/customers/redact"

  [[webhooks.subscriptions]]
  topics = [ "shop/redact" ]
  uri = "/webhooks/shop/redact"


[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_orders,write_orders,read_themes,read_content,write_content,write_pixels,read_customer_events,read_own_subscription_contracts,write_own_subscription_contracts"

[auth]
redirect_urls = [
  "https://trlklwixfeaexhydzaue.supabase.co/functions/v1/shopify-auth-callback"
]


[pos]
embedded = false


