import React, { useState, useCallback } from 'react';
import { Plus, Copy, Edit, Trash2, Download, Upload } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { toast } from 'sonner';
import {
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableFooter,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"
import { Textarea } from "@/components/ui/textarea"
import { useI18n } from '@/lib/i18n';
import { useToast } from '@/hooks/use-toast';
import { useSupabase } from '@/lib/supabase-provider';
import { v4 as uuidv4 } from 'uuid';
import { useRouter } from 'next/navigation';
import { useNavigate } from 'react-router-dom';
import { useShopify } from '@/hooks/useShopify';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { AlertCircle } from 'lucide-react';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"
import { MoreVertical } from 'lucide-react';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { Progress } from "@/components/ui/progress"
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form"
import { z } from "zod"
import { zodResolver } from "@hookform/resolvers/zod"
import { useForm } from "react-hook-form"
import { ConnectionSynchronizer } from '@/components/form/builder/ConnectionSynchronizer';
import { shopifyConnectionManager } from '@/lib/shopify/connection-manager';
import { connectionLogger } from '@/lib/shopify/debug-logger';
import { supabase } from '@/integrations/supabase/client';
import { ShopifyConnectionStatus } from '@/components/form/builder/ShopifyConnectionStatus';

interface FormsPageProps {
  shopId?: string | null;
}

const FormsPage: React.FC<FormsPageProps> = ({ shopId }) => {
  const { language } = useI18n();
  const { supabaseClient } = useSupabase();
  const [forms, setForms] = useState<any[]>([]);
  const [isSaving, setIsSaving] = useState(false);
  const [isDeleting, setIsDeleting] = useState(false);
  const [isImporting, setIsImporting] = useState(false);
  const [isExporting, setIsExporting] = useState(false);
  const [selectedForm, setSelectedForm] = useState<any>(null);
  const [isCreating, setIsCreating] = useState(false);
  const [isEditing, setIsEditing] = useState(false);
  const [newFormName, setNewFormName] = useState('');
  const [editFormName, setEditFormName] = useState('');
  const [importData, setImportData] = useState('');
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [isSyncing, setIsSyncing] = useState(false);
  const [syncStatus, setSyncStatus] = useState<string | null>(null);
  const [isResyncing, setIsResyncing] = useState(false);
  const [resyncProgress, setResyncProgress] = useState(0);
  const [resyncError, setResyncError] = useState<string | null>(null);
  const [isShopifyConnected, setIsShopifyConnected] = useState(false);
  const [shopifyStoreId, setShopifyStoreId] = useState<string | null>(null);
  const [connectionError, setConnectionError] = useState<string | null>(null);
  const [isVerifyingConnection, setIsVerifyingConnection] = useState(false);
  const [isConnectionForced, setIsConnectionForced] = useState(false);
  const [isConnectionValidating, setIsConnectionValidating] = useState(false);
  const [isConnectionSyncing, setIsConnectionSyncing] = useState(false);
  const [isConnectionResetting, setIsConnectionResetting] = useState(false);
  const [isConnectionTesting, setIsConnectionTesting] = useState(false);
  const [isConnectionCleaning, setIsConnectionCleaning] = useState(false);
  const [isConnectionActivating, setIsConnectionActivating] = useState(false);
  const [isConnectionDeactivating, setIsConnectionDeactivating] = useState(false);
  const [isConnectionSyncingDatabase, setIsConnectionSyncingDatabase] = useState(false);
  const [isConnectionSyncingLocalStorage, setIsConnectionSyncingLocalStorage] = useState(false);
  const [isConnectionSyncingConnectionManager, setIsConnectionSyncingConnectionManager] = useState(false);
  const [isConnectionSyncingAll, setIsConnectionSyncingAll] = useState(false);
  const [isConnectionSyncingAllDatabase, setIsConnectionSyncingAllDatabase] = useState(false);
  const [isConnectionSyncingAllLocalStorage, setIsConnectionSyncingAllLocalStorage] = useState(false);
  const [isConnectionSyncingAllConnectionManager, setIsConnectionSyncingAllConnectionManager] = useState(false);
  const [isConnectionSyncingAllComplete, setIsConnectionSyncingAllComplete] = useState(false);
  const [isConnectionSyncingAllError, setIsConnectionSyncingAllError] = useState<string | null>(null);
  const [isConnectionSyncingAllProgress, setIsConnectionSyncingAllProgress] = useState(0);
  const [isConnectionSyncingAllTotal, setIsConnectionSyncingAllTotal] = useState(0);
  const [isConnectionSyncingAllCurrent, setIsConnectionSyncingAllCurrent] = useState<string | null>(null);
  const [isConnectionSyncingAllCurrentProgress, setIsConnectionSyncingAllCurrentProgress] = useState(0);
  const [isConnectionSyncingAllCurrentTotal, setIsConnectionSyncingAllCurrentTotal] = useState(0);
  const [isConnectionSyncingAllCurrentError, setIsConnectionSyncingAllCurrentError] = useState<string | null>(null);
  const [isConnectionSyncingAllCurrentComplete, setIsConnectionSyncingAllCurrentComplete] = useState(false);
  const [isConnectionSyncingAllCurrentCancelled, setIsConnectionSyncingAllCurrentCancelled] = useState(false);
  const [isConnectionSyncingAllCurrentCancelledError, setIsConnectionSyncingAllCurrentCancelledError] = useState<string | null>(null);
  const [isConnectionSyncingAllCurrentCancelledComplete, setIsConnectionSyncingAllCurrentCancelledComplete] = useState(false);
  const [isConnectionSyncingAllCurrentCancelledProgress, setIsConnectionSyncingAllCurrentCancelledProgress] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledTotal, setIsConnectionSyncingAllCurrentCancelledTotal] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrent, setIsConnectionSyncingAllCurrentCancelledCurrent] = useState<string | null>(null);
  const [isConnectionSyncingAllCurrentCancelledCurrentProgress, setIsConnectionSyncingAllCurrentCancelledCurrentProgress] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentTotal, setIsConnectionSyncingAllCurrentCancelledCurrentTotal] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentError, setIsConnectionSyncingAllCurrentCancelledCurrentError] = useState<string | null>(null);
  const [isConnectionSyncingAllCurrentCancelledCurrentComplete, setIsConnectionSyncingAllCurrentCancelledCurrentComplete] = useState(false);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelled, setIsConnectionSyncingAllCurrentCancelledCurrentCancelled] = useState(false);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledError, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledError] = useState<string | null>(null);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledComplete, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledComplete] = useState(false);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledProgress, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledProgress] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledTotal, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledTotal] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrent, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrent] = useState<string | null>(null);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentProgress, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentProgress] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentTotal, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentTotal] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentError, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentError] = useState<string | null>(null);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentComplete, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentComplete] = useState(false);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelled, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelled] = useState(false);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledError, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledError] = useState<string | null>(null);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledComplete, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledComplete] = useState(false);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledProgress, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledProgress] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledTotal, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledTotal] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrent, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrent] = useState<string | null>(null);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentProgress, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentProgress] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentTotal, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentTotal] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentError, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentError] = useState<string | null>(null);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentComplete, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentComplete] = useState(false);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelled, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelled] = useState(false);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledError, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledError] = useState<string | null>(null);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledComplete, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledComplete] = useState(false);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledProgress, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledProgress] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledTotal, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledTotal] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrent, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrent] = useState<string | null>(null);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentProgress, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentProgress] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentTotal, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentTotal] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentError, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentError] = useState<string | null>(null);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentComplete, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentComplete] = useState(false);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelled, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelled] = useState(false);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledError, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledError] = useState<string | null>(null);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledComplete, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledComplete] = useState(false);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledProgress, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledProgress] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledTotal, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledTotal] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrent, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrent] = useState<string | null>(null);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentProgress, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentProgress] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentTotal, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentTotal] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentError, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentError] = useState<string | null>(null);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentComplete, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentComplete] = useState(false);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelled, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelled] = useState(false);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledError, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledError] = useState<string | null>(null);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledComplete, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledComplete] = useState(false);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledProgress, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledProgress] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledTotal, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledTotal] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrent, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrent] = useState<string | null>(null);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentProgress, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentProgress] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentTotal, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentTotal] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentError, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentError] = useState<string | null>(null);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentComplete, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentComplete] = useState(false);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelled, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelled] = useState(false);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledError, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledError] = useState<string | null>(null);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledComplete, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledComplete] = useState(false);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledProgress, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledProgress] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledTotal, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledTotal] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrent, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrent] = useState<string | null>(null);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentProgress, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentProgress] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentTotal, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentTotal] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentError, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentError] = useState<string | null>(null);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentComplete, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentComplete] = useState(false);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelled, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelled] = useState(false);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledError, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledError] = useState<string | null>(null);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledComplete, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledComplete] = useState(false);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledProgress, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledProgress] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledTotal, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledTotal] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrent, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrent] = useState<string | null>(null);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentProgress, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledProgress] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentTotal, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledTotal] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentError, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledError] = useState<string | null>(null);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentComplete, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledComplete] = useState(false);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelled, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCancelled] = useState(false);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledError, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCancelledError] = useState<string | null>(null);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledComplete, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCancelledComplete] = useState(false);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledProgress, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCancelledProgress] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledTotal, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCancelledTotal] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrent, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrent] = useState<string | null>(null);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentProgress, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentProgress] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentTotal, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentTotal] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentError, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentError] = useState<string | null>(null);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentComplete, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentComplete] = useState(false);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelled, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelled] = useState(false);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledError, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledError] = useState<string | null>(null);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledComplete, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledComplete] = useState(false);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledProgress, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledProgress] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledTotal, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledTotal] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrent, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrent] = useState<string | null>(null);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentProgress, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentProgress] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentTotal, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentTotal] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentError, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentError] = useState<string | null>(null);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentComplete, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentComplete] = useState(false);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelled, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelled] = useState(false);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledError, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledError] = useState<string | null>(null);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledComplete, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledComplete] = useState(false);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledProgress, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledProgress] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledTotal, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledTotal] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledCurrent, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledCurrent] = useState<string | null>(null);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledProgress, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledProgress] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledTotal, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledTotal] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledError, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledError] = useState<string | null>(null);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledComplete, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledComplete] = useState(false);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledCancelled, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledCancelled] = useState(false);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledCancelledError, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledCancelledError] = useState<string | null>(null);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledCancelledComplete, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledCancelledComplete] = useState(false);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledCancelledProgress, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledCancelledProgress] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledCancelledTotal, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledCancelledTotal] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledCancelledCurrent, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledCancelledCurrent] = useState<string | null>(null);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledCancelledProgress, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledCancelledProgress] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledCancelledTotal, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledCancelledTotal] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledCancelledError, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledCancelledError] = useState<string | null>(null);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledCancelledComplete, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledCancelledComplete] = useState(false);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledCancelledCancelled, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledCancelledCancelled] = useState(false);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledCancelledCancelledError, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledCancelledCancelledError] = useState<string | null>(null);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledCancelledCancelledComplete, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledCancelledCancelledComplete] = useState(false);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledCancelledCancelledProgress, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledCancelledCancelledProgress] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledCancelledCancelledTotal, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledCancelledCancelledTotal] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledCancelledCancelledCurrent, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledCancelledCancelledCurrent] = useState<string | null>(null);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledCancelledCancelledProgress, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledCancelledCancelledProgress] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledCancelledCancelledTotal, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledCancelledCancelledTotal] = useState(0);
  const [isConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledCancelledCancelledError, setIsConnectionSyncingAllCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCancelledCurrentCurrentCancelledCurrentCancelledCancelledCancelledError] = useState<string | null>(null
