name = "CODFORM Admin Action"
type = "ui_extension"
handle = "admin-action-extension"

[[metafields]]
namespace = "codform"
key = "settings"

[[extensions.targeting]]
module = "./src/ActionExtension.jsx"
target = "admin.product-details.action.render"
