
name = "CODFORM Admin Action"
type = "ui_extension"
handle = "admin-action-extension"

[[metafields]]
namespace = "codform"
key = "settings"

[extension_points]
target = "admin.product-details.action.render"
module = "./src/ActionExtension.jsx"
