
name = "CODFORM - نماذج الدفع عند الاستلام"
type = "theme"
handle = "theme-extension-codform"

[[metafields]]
namespace = "codform"
key = "settings"

[[extensions.blocks]]
name = "نموذج الدفع عند الاستلام"
handle = "codform_form"
type = "product"
target = "section"

[extensions.settings]
# Global extension settings

[javascript]
codform-core = "assets/codform-core.js"

[css]
codform-styles = "assets/codform-styles.css"

