
name = "CODFORM - نماذج الدفع عند الاستلام"
type = "theme"
handle = "theme-extension-codform"

[[metafields]]
namespace = "codform"
key = "settings"

[[extensions.blocks]]
name = "نموذج الدفع عند الاستلام"
handle = "codform_form"
type = "product"
target = "section"

[extensions.settings]
# Global extension settings
fields = [
  {
    "key": "insertion_method",
    "type": "select",
    "label": { "en": "Form Insertion Method", "ar": "طريقة إدراج النموذج" },
    "options": [
      { "value": "auto", "label": { "en": "Automatic", "ar": "تلقائي" } },
      { "value": "manual", "label": { "en": "Manual", "ar": "يدوي" } }
    ],
    "default": "manual"
  }
]
